<?php

declare(strict_types=1);

namespace Setono\Deployer\DotEnv\Integration;

use phpseclib3\Crypt\PublicKeyLoader;
use phpseclib3\Net\SSH2;
use PHPUnit\Framework\TestCase;

final class DeployerTest extends TestCase
{
    protected function assertPreConditions(): void
    {
        self::assertFileExists(__DIR__ . '/deploy.php');
    }

    /**
     * @test
     */
    public function it_deploys(): void
    {
        exec(sprintf('cd %s && php %s deploy -n', __DIR__, '../../vendor/bin/dep'), $output, $return);

        $this->assertSame(0, $return);

        $key = PublicKeyLoader::load(file_get_contents(__DIR__ . '/../docker/ssh/id_rsa'));

        $ssh = new SSH2('127.0.0.1', 2222);
        if (!$ssh->login('root', $key)) {
            throw new \RuntimeException('Could not connection to the server');
        }

        $releasePath = trim($ssh->exec('realpath ~/deployer/current'));
        self::assertIsString($releasePath);

        self::assertSame('APP_ENV=prod', trim($ssh->exec(sprintf('cat %s/.env.local', $releasePath))));
        self::assertSame(<<<CONTENT
<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'MAILER_DSN' => 'smtp://localhost',
);
CONTENT
            , trim($ssh->exec(sprintf('cat %s/.env.local.php', $releasePath))));
    }
}
